#!/usr/bin/env bash
# Install a polkit rule so the droppix evdi streamer can be launched via pkexec
# WITHOUT a password prompt every time you Start streaming.
#
# The streamer needs root (evdi's add_device), so the GUI runs it as `pkexec
# droppix_stream`, which prompts by default. This rule pre-authorizes only that
# exact binary, only for your user.
#
# Usage (the repo is on a no-exec mount, so run it with bash):
#   bash scripts/install-polkit-rule.sh [path/to/droppix_stream]
# Default binary path: $HOME/droppix-build/droppix_stream
#
# Security note: the rule grants passwordless root execution of that binary to your
# user. If the binary lives in a directory you can write to, that is effectively
# passwordless root for your account. For a tighter setup, install droppix_stream to a
# root-owned path (e.g. /usr/local/bin) and pass that path here.
set -euo pipefail

BIN="${1:-$HOME/droppix-build/droppix_stream}"
BIN_REAL="$(realpath -- "$BIN" 2>/dev/null || true)"
if [ -z "$BIN_REAL" ] || [ ! -x "$BIN_REAL" ]; then
  echo "error: droppix_stream not found/executable at: $BIN" >&2
  echo "       pass the path explicitly: bash $0 /path/to/droppix_stream" >&2
  exit 1
fi
USER_NAME="$(id -un)"
RULE=/etc/polkit-1/rules.d/49-droppix.rules

echo "Authorizing passwordless pkexec:"
echo "  binary: $BIN_REAL"
echo "  user:   $USER_NAME"
echo "  rule:   $RULE"

sudo tee "$RULE" >/dev/null <<EOF
// droppix: passwordless pkexec for the evdi streamer. Generated by install-polkit-rule.sh.
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.policykit.exec" &&
        action.lookup("program") == "$BIN_REAL" &&
        subject.user == "$USER_NAME") {
        return polkit.Result.YES;
    }
});
EOF

echo "Installed. polkitd reloads automatically — Start streaming should no longer prompt."
echo "To undo:  sudo rm $RULE"
