#!/usr/bin/env bash
# Install a polkit rule so the droppix evdi streamer (launched via `pkexec
# droppix_stream`, which needs root for evdi's add_device) doesn't prompt for a
# password on every Start. The rule pre-authorizes only that exact binary, only for
# your user.
#
# Two modes:
#   (default)        authenticate ONCE per login, then remembered until you log out /
#                    reboot  (polkit AUTH_SELF_KEEP)
#   --passwordless   never prompt at all  (polkit YES)
#
# Usage (the repo is on a no-exec mount, so run it with bash):
#   bash scripts/install-polkit-rule.sh [--passwordless] [path/to/droppix_stream]
# Default binary path: $HOME/droppix-build/droppix_stream
#
# Security note: with --passwordless the binary can be run as root with no auth; if it
# lives in a directory you can write to, that is effectively passwordless root for your
# account. The default (auth-once-per-login) keeps a single password gate per session.
# For the tightest setup, install droppix_stream to a root-owned path and pass it here.
set -euo pipefail

MODE=keep
ARGS=()
for a in "$@"; do
  case "$a" in
    --passwordless|--always|--yes) MODE=yes ;;
    --keep|--once)                 MODE=keep ;;
    *)                             ARGS+=("$a") ;;
  esac
done

BIN="${ARGS[0]:-$HOME/droppix-build/droppix_stream}"
BIN_REAL="$(realpath -- "$BIN" 2>/dev/null || true)"
if [ -z "$BIN_REAL" ] || [ ! -x "$BIN_REAL" ]; then
  echo "error: droppix_stream not found/executable at: $BIN" >&2
  echo "       pass the path explicitly: bash $0 [--passwordless] /path/to/droppix_stream" >&2
  exit 1
fi
USER_NAME="$(id -un)"
RULE=/etc/polkit-1/rules.d/49-droppix.rules

if [ "$MODE" = yes ]; then
  RESULT="polkit.Result.YES";            DESC="passwordless (never prompts)"
else
  RESULT="polkit.Result.AUTH_SELF_KEEP"; DESC="authenticate once per login, then remembered"
fi

echo "Authorizing pkexec — $DESC:"
echo "  binary: $BIN_REAL"
echo "  user:   $USER_NAME"
echo "  rule:   $RULE"

sudo tee "$RULE" >/dev/null <<EOF
// droppix: pre-authorize pkexec for the evdi streamer. Generated by install-polkit-rule.sh.
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.policykit.exec" &&
        action.lookup("program") == "$BIN_REAL" &&
        subject.user == "$USER_NAME") {
        return $RESULT;
    }
});
EOF

echo "Installed. polkitd reloads automatically."
echo "To undo:  sudo rm $RULE"
